# Site
name: "askPio"
description: "askPio, Bot, AI, LUIS"
meta_description: "askPio blog"
logo: 'logo/askpio-logo.svg'
favicon_content: "https://content.askpio.com/favicon/"
content: "https://content.askpio.com/"
favicon: 'favicon.ico'
baseurl: ''
mainurl: 'https://askpio.com'
appmainurl: 'https://app.askpio.com'
google_analytics: 'UA-132318762-1'
disqus: 'https-blog-subwai-com'
mailchimp-list: 'https://subwai.us20.list-manage.com/subscribe/post?u=e01c7eea6ace40984a93be00d&amp;id=98ff40b631'

# Authors
authors:
  sal:
    name: askPio Team
    display_name: askPio Team
    gravatar: e3de54ef7eac1555249ce3b2e8109eee
    email: info.askpio@gmail.com
    web: https://blog.askpio.com
    twitter: https://twitter.com/AskPio
    description: "Askpio Description"
  harsh:
    name: Harsh Gupta  
    display_name: Harsh Gupta
    gravatar: e3de54ef7eac1555249ce3b2e8109eee
    email: info.askpio@gmail.com
    web: https://blog.askpio.com
    twitter: https://twitter.com/AskPio
    description: "He is working in Vineforce IT Services Pvt. Ltd. as a Development Lead, which is a development branch of Vineforce Inc.."
  rinkal:
    name: Rinkal Jindal  
    display_name: Rinkal Jindal
    gravatar: e3de54ef7eac1555249ce3b2e8109eee
    email: info.askpio@gmail.com
    web: https://blog.askpio.com
    twitter: https://twitter.com/AskPio
    description: "R&D department of Askpio.com"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
