# Site
name: "Subwai"
description: "Subwai, Bot, AI, LUIS"
meta_description: "Subwai blog"
logo: 'assets/images/logo.png'
favicon: '/favicon.ico'
baseurl: ''
mainurl: 'http://subwai.com'
google_analytics: 'UA-132318762-1'
disqus: 'demowebsite'
mailchimp-list: 'https://subwai.us20.list-manage.com/subscribe/post?u=e01c7eea6ace40984a93be00d&amp;id=98ff40b631'

# Authors
authors:
  sal:
    name: Harsh
    display_name: Harsh
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: harshdeepgupta49@gmail.com
    web: https://subwai.com
    twitter: https://twitter.com/
    description: "Subwai Description"
  john:
    name: Rinkal  
    display_name: Rinkal
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: info.subwai@gmail.com
    web: https://blog.subwai.net
    twitter: https://twitter.com/Subwai1
    description: "This is the author box."
  rinkal:
    name: Rinkal  
    display_name: Rinkal
    gravatar: 35be3d2ebffa6d9ee03e64328e6988eb
    email: info.subwai@gmail.com
    web: https://blog.subwai.net
    twitter: https://twitter.com/Subwai1
    description: "She is working in R&D department of Subwai.com"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
